### ISSUE TITLE
Projet actif ?

### ISSUE THREAD

**Issue by ursidal** [ClubExpressions/clubexpr-web#2]
Bonjour,
Je trouve le Club des Expressions très intéressant et je pense l'utiliser avec mes classes l'année prochaine mais j'aimerais pouvoir proposer des améliorations (l'apparence sur mobile, créer des expressions sans passer par le générateur,...). 
Est-ce que le projet est encore actif ? Si oui, je n'ai pas réussi à le lancer chez moi (où est l'image docker dont parle le ReadMe ?), pouvez-vous mettre à disposition ce qu'il manque pour faire tourner le club et tester des modifications ?

**Comment by Grahack** [comment]
Bonjour, merci pour ton intérêt. Le projet est encore actif en quelque sorte même si je ne l'ai fait évoluer depuis sa sortie.
Désolé pour la fausse piste docker. J'avais du essayer mais sans pouvoir aboutir. La seule façon de tester des modifications sur le projet et installer toute la pile du développeur. Redis-moi si tu as des problèmes.

**Comment by Grahack** [comment]
Et si tu veux en parler au téléphone, je suis au 06 61 80 41 69.

**Comment by ursidal** [comment]
Merci pour ta réponse rapide ! Ça m'a permis de comprendre que le problème ne venait pas de l'absence de Kinto et Postgresql. C'était une erreur de compilation de java (auquel je ne connais pas grand-chose...), j'ai essayé de mettre toutes les dépendances à jour mais cela à créer un problème avec le bundle qui fournit react. Finalement il suffit de ne toucher à rien et d'utiliser java8 (j'avais la version 11 par défaut). Je vais commencer à mettre les mains dans le cambouis.

**Comment by Grahack** [comment]
J'ai eu récemment un problème avec Kinto je suis obligé de développer face à la base de production. Il y a d'autres loose dans le genre. Je te tiendrai au courant.

**Comment by Grahack** [comment]
Le mieux serait un petit coup de fil demain matin.
